export const ACTION_TYPE = {
    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
    LOGOUT: 'LOGOUT',
    RESET_POST_DATA: 'RESET_POST_DATA',
    SET_USER: 'SET_USER',
    SET_POST_DATA: 'SET_POST_DATA',
};
